### ISSUE TITLE
运行报错 md5不匹配

### ISSUE THREAD

**Issue by guyingd** [ShizukuLostWorld/Hana_ZeroBot#1]
`ERRO[0002] [file]文件 data/Control/kanban.png md5不匹配, 下载失败
panic: file md5 mismatch`

`goroutine 1 [running]:                                                                  github.com/FloatTech/zbputils/control.init.2()
        /root/go/pkg/mod/github.com/!float!tech/zbputils@v1.5.1-0.20220912115535-0bd7af2e70c6/control/servicepic.go:67 +0x9c`

运行平台：
Android 
Termux
chroot容器 Arch linux
![IMG_20221004_200415](https://user-images.githubusercontent.com/79262296/193814874-77f4a2b9-98b9-4eff-825d-d7c19b78e1ce.jpg)

**Comment by guyingd** [comment]
源码运行和自编译运行都有这个报错

**Comment by MoYoez** [comment]
a....这个是咱的分支 有很多魔改的地方哦 真的要跑嘛x

**Comment by guyingd** [comment]
> 

半成品吗？

**Comment by MoYoez** [comment]
> > 
> 
> 半成品吗？

具体来说是没有对外公开用的 有能力的话可以自己改
主要是魔改了一堆 没有做格式化的应用 

如果真的要用这个版本的话 咱可以加好友帮你弄

原版是 https://github.com/FloatTech/ZeroBot-Plugin

**Comment by MoYoez** [comment]
> > > 
> > 
> > 
> > 半成品吗？
> 
> 具体来说是没有对外公开用的 有能力的话可以自己改 主要是魔改了一堆 没有做格式化的应用
> 
> 如果真的要用这个版本的话 咱可以加好友帮你弄
> 
> 原版是 https://github.com/FloatTech/ZeroBot-Plugin

原版的zbp是GPL3.0 如果修改了是必须要放出源码的

**Comment by MoYoez** [comment]
> > 
> 
> 半成品吗？

这个是咱qq号: 1292581422

**Comment by guyingd** [comment]
我能力不够，魔改不了，加你QQ了
